server:
  port: ${PORT}
spring:
  application:
    name: banking-ivr-api
  config:
    import:
    - optional:classpath:/config/soap.services.config.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info